# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        
    - name: Build
      run: go build -o out/dbt-lsp .

    - name: Windows Build
      run: go build -buildmode exe -o out/dbt-lsp.exe .

    - name: release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "out/**"
        tag: 0.0.0.${{ github.run_id }}
        replacesArtifacts: true
        removeArtifacts: true
